// Generated by CoffeeScript 1.3.3
var InsertDownloader;

InsertDownloader = function(urlRegExp) {
  var appendDownloader, bindTabUpdate, downloaderUrl, insertJS;
  downloaderUrl = 'http://127.0.0.1:3000/server/downloader.js';
  bindTabUpdate = function(callback) {
    return chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
      if (changeInfo.status === 'complete') {
        return callback(tabId, tab.url);
      }
    });
  };
  insertJS = function(tabId, path) {
    var code;
    code = '(' + appendDownloader.toString() + '(\'' + path + '\'))';
    return chrome.tabs.executeScript(tabId, {
      code: code
    }, function() {
      return console.log('Taist extension: insert JS', tabId, path);
    });
  };
  appendDownloader = function(path) {
    var script;
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = path;
    document.body.appendChild(script);
    return console.log('Taist initialization', path);
  };
  console.log('Taist extension: init');
  return bindTabUpdate(function(tabId, url) {
    if (urlRegExp.test(url)) {
      return insertJS(tabId, downloaderUrl);
    }
  });
};
